version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: jokes_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jokes
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
